CREATE TABLE SHOP.CUSTOMER (
	CUSTOMER_ID INTEGER NOT NULL,
	NAME VARCHAR(30) DEFAULT 'NULL',
	ADDRESS VARCHAR(100) DEFAULT 'NULL',
	CITY VARCHAR(20) DEFAULT 'NULL',
	STATE VARCHAR(20) DEFAULT 'NULL',
	EMAIL VARCHAR(50) DEFAULT 'NULL',
	PHONE CHAR(13) DEFAULT 'NULL',
	MESSAGE VARCHAR(550),
	PRIMARY KEY (CUSTOMER_ID)
);
CREATE TABLE SHOP.ORDER_DETAIL (
	ORDER_DETAIL_ID INTEGER NOT NULL,
	COUNT INTEGER DEFAULT NULL,
	PRODUCT_ID INTEGER NOT NULL,
	ORDER_ID INTEGER NOT NULL,
	PRIMARY KEY (ORDER_DETAIL_ID)
);
CREATE TABLE SHOP.ORDER_STATUS (
	ORDER_STATUS_ID INTEGER NOT NULL,
	DESCRIPTION VARCHAR(45) DEFAULT 'NULL',
	PRIMARY KEY (ORDER_STATUS_ID)
);
CREATE TABLE SHOP.ORDERS (
	ORDER_ID INTEGER NOT NULL,
	CREATE_TIME TIMESTAMP DEFAULT NULL,
	PURCHASE_TIME TIMESTAMP DEFAULT NULL,
	CUSTOMER_ID INTEGER NOT NULL,
	ORDER_STATUS_ID INTEGER NOT NULL,
	PRIMARY KEY (ORDER_ID)
);
CREATE TABLE SHOP.PRODUCT (
	PRODUCT_ID INTEGER NOT NULL,
	PRODUCT_NAME VARCHAR(100) NOT NULL,
	PICTURE VARCHAR(100) NOT NULL,
	PRICE DOUBLE NOT NULL,
	DESCRIPTION VARCHAR(1000) DEFAULT 'NULL',
	COUNT INTEGER DEFAULT 1 NOT NULL,
	PRIMARY KEY (PRODUCT_ID)
);
CREATE TABLE SHOP.ROLE (
	ROLE_ID INTEGER NOT NULL,
	DESCRIPTION CHAR(20) NOT NULL,
	PRIMARY KEY (ROLE_ID)
);
CREATE TABLE SHOP.USERS (
	USER_ID INTEGER NOT NULL,
	USERNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	CUSTOMER_ID INTEGER DEFAULT NULL,
	ROLE_ID INTEGER DEFAULT NULL,
	PRIMARY KEY (USER_ID)
);

ALTER TABLE SHOP.ORDER_DETAIL
	ADD FOREIGN KEY (PRODUCT_ID)
	REFERENCES SHOP.PRODUCT (PRODUCT_ID);

ALTER TABLE SHOP.ORDER_DETAIL
	ADD FOREIGN KEY (ORDER_ID)
	REFERENCES SHOP.ORDERS (ORDER_ID);

ALTER TABLE SHOP.ORDERS
	ADD FOREIGN KEY (CUSTOMER_ID)
	REFERENCES SHOP.CUSTOMER (CUSTOMER_ID);

ALTER TABLE SHOP.ORDERS
	ADD FOREIGN KEY (ORDER_STATUS_ID)
	REFERENCES SHOP.ORDER_STATUS (ORDER_STATUS_ID);


ALTER TABLE SHOP.USERS
	ADD FOREIGN KEY (CUSTOMER_ID)
	REFERENCES SHOP.CUSTOMER (CUSTOMER_ID);

ALTER TABLE SHOP.USERS
	ADD FOREIGN KEY (ROLE_ID)
	REFERENCES SHOP.ROLE (ROLE_ID);

/* Customers */
	INSERT INTO SHOP.CUSTOMER(CUSTOMER_ID, NAME, ADDRESS, CITY, STATE, EMAIL, PHONE, MESSAGE) VALUES (1, 'joe', 'joe', 'joe', 'joe', 'joe@gmail.com', '1234567      ', null);
	INSERT INTO SHOP.CUSTOMER(CUSTOMER_ID, NAME, ADDRESS, CITY, STATE, EMAIL, PHONE, MESSAGE) VALUES (2, 'toor', 'toor', 'toor', 'toor', 'toor@gmail.com', '7654321      ', null);
	INSERT INTO SHOP.ROLE(ROLE_ID, DESCRIPTION) VALUES (1, 'normal              ');
	INSERT INTO SHOP.ROLE(ROLE_ID, DESCRIPTION) VALUES (2, 'admin               ');
	INSERT INTO SHOP.USERS(USER_ID, USERNAME, PASSWORD, CUSTOMER_ID, ROLE_ID) VALUES (1, 'joe', '1467136381', 1, 1);
	INSERT INTO SHOP.USERS(USER_ID, USERNAME, PASSWORD, CUSTOMER_ID, ROLE_ID) VALUES (2, 'toor', '-1969301148', 2, 2);
    
/* ORDER_STATUS */
	INSERT INTO SHOP.ORDER_STATUS(ORDER_STATUS_ID, DESCRIPTION) VALUES (1, 'Fresh');
    INSERT INTO SHOP.ORDER_STATUS(ORDER_STATUS_ID, DESCRIPTION) VALUES (2, 'Confirmed');
    INSERT INTO SHOP.ORDER_STATUS(ORDER_STATUS_ID, DESCRIPTION) VALUES (3, 'Cancel');


	INSERT INTO SHOP.PRODUCT(PRODUCT_ID, PRODUCT_NAME, PICTURE, PRICE, DESCRIPTION, "COUNT") VALUES (1, 'mouse', '1', 12.0, 'mouse', 1);
	INSERT INTO SHOP.PRODUCT(PRODUCT_ID, PRODUCT_NAME, PICTURE, PRICE, DESCRIPTION, "COUNT") VALUES (2, 'keyboard', '1', 12.0, 'keyboard', 1);
	INSERT INTO SHOP.PRODUCT(PRODUCT_ID, PRODUCT_NAME, PICTURE, PRICE, DESCRIPTION, "COUNT") VALUES (3, 'mouse', '1', 11.0, 'mouse3', 1);
	INSERT INTO SHOP.PRODUCT(PRODUCT_ID, PRODUCT_NAME, PICTURE, PRICE, DESCRIPTION, "COUNT") VALUES (4, 'keyboard', '1', 20.0, 'keyboard4', 1);
	INSERT INTO SHOP.PRODUCT(PRODUCT_ID, PRODUCT_NAME, PICTURE, PRICE, DESCRIPTION, "COUNT") VALUES (5, 'laptop', '1', 1000.0, 'laptop1', 1);
	INSERT INTO SHOP.PRODUCT(PRODUCT_ID, PRODUCT_NAME, PICTURE, PRICE, DESCRIPTION, "COUNT") VALUES (6, 'laptop-lenovo', '1', 1200.0, 'lenovo', 1);
	INSERT INTO SHOP.PRODUCT(PRODUCT_ID, PRODUCT_NAME, PICTURE, PRICE, DESCRIPTION, "COUNT") VALUES (7, 'dell', '1', 1300.0, 'dell', 1);
	INSERT INTO SHOP.PRODUCT(PRODUCT_ID, PRODUCT_NAME, PICTURE, PRICE, DESCRIPTION, "COUNT") VALUES (8, 'dell', '1', 1305.0, 'dell-1', 20);
	INSERT INTO SHOP.PRODUCT(PRODUCT_ID, PRODUCT_NAME, PICTURE, PRICE, DESCRIPTION, "COUNT") VALUES (9, 'dell', '1', 1305.0, 'dell-2', 5);
